const useAuth = () => {
  try {
  } catch (error) {
    console.log("error:", error);
  }
};
